//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIONLOGDETAIL
    {
        public int ID { get; set; }
        public Nullable<int> MASTERID { get; set; }
        public Nullable<int> FRAMEID { get; set; }
        public Nullable<int> ACTIONID { get; set; }
        public Nullable<int> DATAID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> ACTIONDATE { get; set; }
        public string REMARK { get; set; }
    
        public virtual ACTIONLOGMASTER ACTIONLOGMASTER { get; set; }
    }
}
