//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIONLOGMASTER
    {
        public ACTIONLOGMASTER()
        {
            this.ACTIONLOGDETAILs = new HashSet<ACTIONLOGDETAIL>();
        }
    
        public int ID { get; set; }
        public string IPADDRESS { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> LOGINUSER { get; set; }
        public Nullable<System.DateTime> LOGINDATE { get; set; }
    
        public virtual ICollection<ACTIONLOGDETAIL> ACTIONLOGDETAILs { get; set; }
    }
}
