//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVERAGEEFFICIENCY
    {
        public int ID { get; set; }
        public int FACTORYID { get; set; }
        public Nullable<int> YEARS { get; set; }
        public Nullable<int> MONTHINDEX { get; set; }
        public Nullable<double> AVERAGEPRODUCEEFFICIENCY { get; set; }
        public Nullable<double> AVERAGEATTENDANCE { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUPNAME { get; set; }
        public Nullable<int> WORKERNUMBER { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
