//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseData
    {
        public int ID { get; set; }
        public int Category { get; set; }
        public string ValueMember { get; set; }
        public string DisplayMember { get; set; }
        public Nullable<int> ReadOnly { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
