//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_PO_DATA
    {
        public int poid { get; set; }
        public string code { get; set; }
        public System.DateTime delivery_date { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> factoryid { get; set; }
        public string factory_name { get; set; }
        public Nullable<System.DateTime> floor_delivery_date { get; set; }
        public string customer_name { get; set; }
        public string parent_customer_name { get; set; }
        public string product_type { get; set; }
        public string parent_producd_type { get; set; }
        public Nullable<int> ott_offset { get; set; }
        public Nullable<int> otd_offset { get; set; }
        public Nullable<double> po_qty { get; set; }
        public Nullable<double> unit_price { get; set; }
        public Nullable<double> cash { get; set; }
        public Nullable<double> plan_qty { get; set; }
        public Nullable<double> finish_qty { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> fabric_arrival_date { get; set; }
        public Nullable<System.DateTime> act_cut_start_date { get; set; }
        public Nullable<System.DateTime> act_sew_start_date { get; set; }
        public Nullable<System.DateTime> act_sew_end_date { get; set; }
        public Nullable<System.DateTime> factory_ship_date { get; set; }
        public Nullable<System.DateTime> plan_sew_start_date { get; set; }
        public Nullable<System.DateTime> plan_sew_end_date { get; set; }
        public Nullable<int> order_to_cut_days { get; set; }
        public Nullable<int> order_to_ship_days { get; set; }
        public Nullable<int> cut_to_ship_days { get; set; }
        public Nullable<int> ontime_delivery_status { get; set; }
        public Nullable<int> product_inventory_days { get; set; }
        public Nullable<int> delay_days { get; set; }
        public Nullable<int> fabric_inventory_days { get; set; }
    }
}
