//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDARTEMPLATEDETAIL
    {
        public int ID { get; set; }
        public Nullable<int> TEMPLATEID { get; set; }
        public Nullable<int> DAYOFWEEKINDEX { get; set; }
        public Nullable<double> STARTHOUR { get; set; }
        public Nullable<double> ENDHOUR { get; set; }
        public Nullable<int> ISOT { get; set; }
        public Nullable<int> UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    
        public virtual CALENDARTEMPLATE CALENDARTEMPLATE { get; set; }
    }
}
