//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITYALLOCATION
    {
        public int ID { get; set; }
        public Nullable<int> TYPEID { get; set; }
        public Nullable<int> FACILITYID { get; set; }
        public Nullable<int> PRODUCTIONTYPEID { get; set; }
        public Nullable<int> THEYEAR { get; set; }
        public Nullable<double> M1 { get; set; }
        public Nullable<double> M2 { get; set; }
        public Nullable<double> M3 { get; set; }
        public Nullable<double> M4 { get; set; }
        public Nullable<double> M5 { get; set; }
        public Nullable<double> M6 { get; set; }
        public Nullable<double> M7 { get; set; }
        public Nullable<double> M8 { get; set; }
        public Nullable<double> M9 { get; set; }
        public Nullable<double> M10 { get; set; }
        public Nullable<double> M11 { get; set; }
        public Nullable<double> M12 { get; set; }
    }
}
