//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMPO
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public string CUSTOMERORDERID { get; set; }
        public Nullable<int> PRODUCTTYPEID { get; set; }
        public string PATTERN { get; set; }
        public string PATTERNDESC { get; set; }
        public double AMOUNT { get; set; }
        public System.DateTime DELIVERYDATE { get; set; }
        public Nullable<int> FACTORYVIEWDATEDAYS { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public Nullable<System.DateTime> MASTERMATERIALDATE { get; set; }
        public Nullable<System.DateTime> MASTERMATERIALRECEIVEDDATE { get; set; }
        public Nullable<System.DateTime> MATERIALDATE { get; set; }
        public Nullable<System.DateTime> MATERIALRECEIVEDDATE { get; set; }
        public Nullable<System.DateTime> PREPRODUCTIONEVENTDATE { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public Nullable<double> EFFICIENCY { get; set; }
        public Nullable<int> MERCHANDISER { get; set; }
        public Nullable<int> FACTORYID { get; set; }
        public Nullable<int> EVENTFLOWID { get; set; }
        public Nullable<int> PROCESSROUTEID { get; set; }
        public Nullable<int> ISFIRMORDER { get; set; }
        public string DESCRIPTION { get; set; }
        public string SEASONCD { get; set; }
        public string PROGRAMNO { get; set; }
        public string CUSTOMERSTYLENO { get; set; }
        public string GTMSTATUS { get; set; }
        public Nullable<System.DateTime> CAOTD { get; set; }
        public Nullable<System.DateTime> INITOTT { get; set; }
        public Nullable<System.DateTime> UPDATEDOTT { get; set; }
        public Nullable<System.DateTime> ACTOTT { get; set; }
        public Nullable<int> ACTCUTQTY { get; set; }
        public Nullable<int> ESTCUTQTY { get; set; }
        public Nullable<int> COMPELFACILITY { get; set; }
        public Nullable<int> TOCOMPELNOAHEAD { get; set; }
        public Nullable<System.DateTime> EARLINESSSTARTDATE { get; set; }
        public string LOTNO { get; set; }
        public string REFNO { get; set; }
        public Nullable<System.DateTime> INITDELIVERYDATE { get; set; }
        public Nullable<double> INITEFFICIENCY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string SALESORDERNO { get; set; }
        public Nullable<int> PARENTPRODUCTTYPEID { get; set; }
        public string POTSTEP { get; set; }
        public string POTSTAT { get; set; }
        public Nullable<double> POTFOB { get; set; }
        public Nullable<double> POTCMPGTM { get; set; }
        public string CCC { get; set; }
        public Nullable<System.DateTime> PLANOTT { get; set; }
        public string ALERT { get; set; }
        public Nullable<int> CREATEUSER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string SOKEYID { get; set; }
        public Nullable<int> EXPORTSTATUS { get; set; }
        public Nullable<double> EXPORTAMOUNT { get; set; }
        public Nullable<System.DateTime> EXPORTDATE { get; set; }
        public string INITGROUPNAME { get; set; }
        public Nullable<System.DateTime> CONFIRMDATE { get; set; }
        public Nullable<int> LOCKFTY { get; set; }
        public Nullable<System.DateTime> PLACEORDERDATE { get; set; }
        public Nullable<int> LOCKPREPRODUCTDATE { get; set; }
        public Nullable<int> LOCKMASTERDATE { get; set; }
        public Nullable<int> LOCKMASTERRECEIVEDDATE { get; set; }
        public Nullable<int> LOCKMATERIALDATE { get; set; }
        public Nullable<int> LOCKMATERIALRECEIVEDDATE { get; set; }
        public Nullable<int> LOCKCAPACITY { get; set; }
        public string GROUPID { get; set; }
        public Nullable<int> ISTURNSINGLE { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> DELIVERYFIRSTREPLY { get; set; }
        public Nullable<System.DateTime> CFORCASTDATE { get; set; }
        public string SETNO { get; set; }
        public string BARCHARTDISPLAY { get; set; }
        public Nullable<System.DateTime> LASTPRODUCTDATE { get; set; }
        public Nullable<int> ISOUTSOURCED { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public Nullable<double> UNITPRICE { get; set; }
        public Nullable<System.DateTime> ABSTRACTSTART { get; set; }
        public Nullable<System.DateTime> ABSTRACTEND { get; set; }
    }
}
