//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EB_AMO_ORDER_LOG
    {
        public string pocode { get; set; }
        public System.DateTime actiontime { get; set; }
        public string actiontype { get; set; }
        public int lineid { get; set; }
        public string amopocode { get; set; }
        public string amopocolor { get; set; }
        public string actionlog { get; set; }
    }
}
