//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EB_AMO_DEFECT
    {
        public string po_code { get; set; }
        public int lineid { get; set; }
        public System.DateTime production_date { get; set; }
        public string po_color { get; set; }
        public int defect_qty { get; set; }
        public string defect_type_code { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public Nullable<System.DateTime> download_date { get; set; }
    }
}
