//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EB_PROGRESS_TRANS
    {
        public int id { get; set; }
        public int scheduleid { get; set; }
        public System.DateTime productiondate { get; set; }
        public int qty { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<int> periodid { get; set; }
        public Nullable<int> userid { get; set; }
    }
}
