//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EB_PO_STATUS_HIST
    {
        public int id { get; set; }
        public int scheduleid { get; set; }
        public int lineid { get; set; }
        public Nullable<System.DateTime> actiontime { get; set; }
        public int status { get; set; }
    }
}
