//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EB_PERIOD_DEFECT
    {
        public int id { get; set; }
        public Nullable<int> scheduleid { get; set; }
        public int periodid { get; set; }
        public string periodname { get; set; }
        public Nullable<int> defectqty { get; set; }
        public Nullable<decimal> defectpercent { get; set; }
        public string defectreason { get; set; }
        public string defectflag { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<int> active { get; set; }
        public string periodcolor { get; set; }
        public Nullable<int> lineid { get; set; }
    }
}
