//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EB_SCHEDULE
    {
        public int id { get; set; }
        public string pocode { get; set; }
        public int lineid { get; set; }
        public Nullable<int> scheduledqty { get; set; }
        public Nullable<decimal> capacity { get; set; }
        public Nullable<int> workers { get; set; }
        public Nullable<int> taskseconds { get; set; }
        public Nullable<int> potargetqty { get; set; }
        public Nullable<int> pofinishedqty { get; set; }
        public Nullable<int> poefficiency { get; set; }
        public string poefficiencyflag { get; set; }
        public Nullable<int> dailytargetqty { get; set; }
        public Nullable<int> dailyfinishedqty { get; set; }
        public Nullable<int> dailyefficiency { get; set; }
        public string dailyefficiencyflag { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string amopocode { get; set; }
        public string amopocolor { get; set; }
        public Nullable<decimal> pousedhours { get; set; }
        public Nullable<decimal> dailyusedhours { get; set; }
        public Nullable<int> amoworkers { get; set; }
    }
}
