//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTFLOWNODE
    {
        public EVENTFLOWNODE()
        {
            this.POEVENTs = new HashSet<POEVENT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EVENTFLOWID { get; set; }
        public Nullable<int> CRITICALEVENTID { get; set; }
        public string PREVNODEID { get; set; }
        public string NEXTNODEID { get; set; }
        public Nullable<double> DURATION { get; set; }
        public Nullable<int> GRAPHICX { get; set; }
        public Nullable<int> GRAPHICY { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ISAFFECTPLAN { get; set; }
        public Nullable<int> FLOWNO { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    
        public virtual CRITICALEVENT CRITICALEVENT { get; set; }
        public virtual EVENTFLOW EVENTFLOW { get; set; }
        public virtual ICollection<POEVENT> POEVENTs { get; set; }
    }
}
