//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_V_PO
    {
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<int> factoryid { get; set; }
        public string factoryname { get; set; }
        public Nullable<int> producttypeid { get; set; }
        public string producttypename { get; set; }
        public Nullable<int> status { get; set; }
        public string statusname { get; set; }
        public Nullable<int> isfirmorder { get; set; }
        public string isfirmordername { get; set; }
        public Nullable<int> eventflowid { get; set; }
        public string eventflowname { get; set; }
        public Nullable<int> processrouteid { get; set; }
        public string processroutename { get; set; }
        public double amount { get; set; }
        public string pattern { get; set; }
        public string customerstyleno { get; set; }
        public Nullable<int> customerid { get; set; }
        public string customername { get; set; }
        public Nullable<double> capacity { get; set; }
        public Nullable<int> merchandiser { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> mastermaterialdate { get; set; }
        public Nullable<System.DateTime> mastermaterialreceiveddate { get; set; }
        public Nullable<System.DateTime> materialdate { get; set; }
        public Nullable<System.DateTime> materialreceiveddate { get; set; }
        public System.DateTime deliverydate { get; set; }
        public Nullable<System.DateTime> initdeliverydate { get; set; }
        public Nullable<System.DateTime> earlinessstartdate { get; set; }
        public Nullable<System.DateTime> preproductioneventdate { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<double> duration { get; set; }
        public Nullable<System.DateTime> ExFactoryDate { get; set; }
        public Nullable<int> WorkDeliverydate { get; set; }
    }
}
