//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACILITY
    {
        public FACILITY()
        {
            this.PRODUCTTYPECAPACITies = new HashSet<PRODUCTTYPECAPACITY>();
            this.FACILITYEFFICIENCies = new HashSet<FACILITYEFFICIENCY>();
            this.LNCURVEAPPLies = new HashSet<LNCURVEAPPLY>();
            this.PLANFACILITYPERMISSIONs = new HashSet<PLANFACILITYPERMISSION>();
            this.SPECIALCALENDARs = new HashSet<SPECIALCALENDAR>();
            this.FACILITYWORKERNUMBERs = new HashSet<FACILITYWORKERNUMBER>();
            this.PRODUCTIONEVENTs = new HashSet<PRODUCTIONEVENT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FACTORYID { get; set; }
        public string GROUPNAME { get; set; }
        public string NAME { get; set; }
        public string LEADER { get; set; }
        public Nullable<int> PROCESSID { get; set; }
        public Nullable<int> WORKERNUMBER { get; set; }
        public Nullable<int> STATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ISSUBCON { get; set; }
        public Nullable<int> MAKEDAYCOUNT { get; set; }
        public Nullable<int> DYNAMICWORKERNUMBER { get; set; }
        public Nullable<int> DYNAMICEFFICIENCY { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    
        public virtual ICollection<PRODUCTTYPECAPACITY> PRODUCTTYPECAPACITies { get; set; }
        public virtual ICollection<FACILITYEFFICIENCY> FACILITYEFFICIENCies { get; set; }
        public virtual ICollection<LNCURVEAPPLY> LNCURVEAPPLies { get; set; }
        public virtual ICollection<PLANFACILITYPERMISSION> PLANFACILITYPERMISSIONs { get; set; }
        public virtual ICollection<SPECIALCALENDAR> SPECIALCALENDARs { get; set; }
        public virtual ICollection<FACILITYWORKERNUMBER> FACILITYWORKERNUMBERs { get; set; }
        public virtual FACTORY FACTORY { get; set; }
        public virtual PROCESS PROCESS { get; set; }
        public virtual ICollection<PRODUCTIONEVENT> PRODUCTIONEVENTs { get; set; }
    }
}
