//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTORY
    {
        public FACTORY()
        {
            this.CALENDARCONTROLs = new HashSet<CALENDARCONTROL>();
            this.FACILITies = new HashSet<FACILITY>();
            this.HOLIDAYs = new HashSet<HOLIDAY>();
            this.LNCURVETEMPLATEAPPLies = new HashSet<LNCURVETEMPLATEAPPLY>();
            this.MACHINEINVENTORies = new HashSet<MACHINEINVENTORY>();
            this.POes = new HashSet<PO>();
            this.PRODUCTIONEVENTDETAILs = new HashSet<PRODUCTIONEVENTDETAIL>();
            this.WORKSHOPs = new HashSet<WORKSHOP>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ISOUTSIDE { get; set; }
        public string DESCRIPTION { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<double> CAPACITY { get; set; }
    
        public virtual ICollection<CALENDARCONTROL> CALENDARCONTROLs { get; set; }
        public virtual ICollection<FACILITY> FACILITies { get; set; }
        public virtual ICollection<HOLIDAY> HOLIDAYs { get; set; }
        public virtual ICollection<LNCURVETEMPLATEAPPLY> LNCURVETEMPLATEAPPLies { get; set; }
        public virtual ICollection<MACHINEINVENTORY> MACHINEINVENTORies { get; set; }
        public virtual ICollection<PO> POes { get; set; }
        public virtual ICollection<PRODUCTIONEVENTDETAIL> PRODUCTIONEVENTDETAILs { get; set; }
        public virtual ICollection<WORKSHOP> WORKSHOPs { get; set; }
    }
}
