//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRPTMASTER
    {
        public int ID { get; set; }
        public Nullable<int> DATASOURCEID { get; set; }
        public string RPTCODE { get; set; }
        public string RPTTITLE { get; set; }
        public string UNIT { get; set; }
        public Nullable<int> DISPLAYSORT { get; set; }
        public Nullable<int> DISPLAYGROUP { get; set; }
        public Nullable<int> DISPLAYFORMAT { get; set; }
        public Nullable<int> REFRESHTIME { get; set; }
        public Nullable<int> REPORTTYPE { get; set; }
        public Nullable<int> RPTENABLED { get; set; }
        public string REMARK { get; set; }
        public string SPNAME { get; set; }
        public string SPPARA { get; set; }
        public string COLOR { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
