//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBALERT
    {
        public int ID { get; set; }
        public string JOBCODE { get; set; }
        public string JOBNAME { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public Nullable<int> VIEWORD { get; set; }
        public string IMAGEPATH { get; set; }
        public Nullable<int> VISIBLE { get; set; }
        public Nullable<int> INFOTYPE { get; set; }
        public Nullable<int> WIDTH { get; set; }
        public string CTRLCODE { get; set; }
    }
}
