//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LANGUAGESETTING
    {
        public string FORMNAME { get; set; }
        public string OBJECTNAME { get; set; }
        public string LANGUAGETYPE { get; set; }
        public string CONTENT { get; set; }
        public string DESCRIPTION { get; set; }
        public string USERTEXT { get; set; }
    }
}
