//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMASTER
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LOGTIME { get; set; }
        public Nullable<System.DateTime> LOGENDTIME { get; set; }
        public Nullable<int> IMPORTCOUNT { get; set; }
        public Nullable<int> UPDATECOUNT { get; set; }
        public Nullable<int> NOCHANGECOUNT { get; set; }
        public Nullable<int> DELETECOUNT { get; set; }
        public Nullable<int> FAILCOUNT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> LOGTYPE { get; set; }
        public Nullable<int> INSERTCOUNT { get; set; }
        public Nullable<int> TOTALCOUNT { get; set; }
    }
}
