//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINEINVENTORY
    {
        public MACHINEINVENTORY()
        {
            this.POMACHINEs = new HashSet<POMACHINE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int AMOUNT { get; set; }
        public int FACTORYID { get; set; }
        public int PROCESSID { get; set; }
        public int OFFSETDAYS { get; set; }
        public double OPERATIONRATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    
        public virtual FACTORY FACTORY { get; set; }
        public virtual ICollection<POMACHINE> POMACHINEs { get; set; }
        public virtual PROCESS PROCESS { get; set; }
    }
}
