//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class macroplan_capacity_loading_ext
    {
        public int ID { get; set; }
        public Nullable<int> factoryid { get; set; }
        public Nullable<System.DateTime> planymd { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> planloading { get; set; }
        public Nullable<int> noplanloading { get; set; }
        public Nullable<int> forecastamount { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    }
}
