//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APSEntities : DbContext
    {
        public APSEntities()
            : base("name=APSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIONLOGDETAIL> ACTIONLOGDETAILs { get; set; }
        public virtual DbSet<ACTIONLOGMASTER> ACTIONLOGMASTERs { get; set; }
        public virtual DbSet<AVERAGEEFFICIENCY> AVERAGEEFFICIENCies { get; set; }
        public virtual DbSet<BaseData> BaseDatas { get; set; }
        public virtual DbSet<CALENDARCONTROL> CALENDARCONTROLs { get; set; }
        public virtual DbSet<CALENDARTEMPLATE> CALENDARTEMPLATEs { get; set; }
        public virtual DbSet<CALENDARTEMPLATEDETAIL> CALENDARTEMPLATEDETAILs { get; set; }
        public virtual DbSet<CAPACITYALLOCATION> CAPACITYALLOCATIONs { get; set; }
        public virtual DbSet<ColumnFixed> ColumnFixeds { get; set; }
        public virtual DbSet<CRITICALEVENT> CRITICALEVENTs { get; set; }
        public virtual DbSet<CRITICALEVENTMAN> CRITICALEVENTMen { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<Customer_ext> Customer_ext { get; set; }
        public virtual DbSet<CustomerEventFlow> CustomerEventFlows { get; set; }
        public virtual DbSet<CUSTOMERGROUPLEVEL2> CUSTOMERGROUPLEVEL2 { get; set; }
        public virtual DbSet<DMLOG> DMLOGs { get; set; }
        public virtual DbSet<EB_AMO_DEFECT> EB_AMO_DEFECT { get; set; }
        public virtual DbSet<EB_AMO_MIGRATION_LOG> EB_AMO_MIGRATION_LOG { get; set; }
        public virtual DbSet<EB_AMO_ORDER_LOG> EB_AMO_ORDER_LOG { get; set; }
        public virtual DbSet<EB_AMO_PO> EB_AMO_PO { get; set; }
        public virtual DbSet<EB_AMO_PROGRESS> EB_AMO_PROGRESS { get; set; }
        public virtual DbSet<EB_DEFECT_TRANS> EB_DEFECT_TRANS { get; set; }
        public virtual DbSet<EB_DEFECT_TYPE> EB_DEFECT_TYPE { get; set; }
        public virtual DbSet<EB_LINE_PERIOD> EB_LINE_PERIOD { get; set; }
        public virtual DbSet<EB_MESSAGE> EB_MESSAGE { get; set; }
        public virtual DbSet<EB_PARAMETER> EB_PARAMETER { get; set; }
        public virtual DbSet<EB_PERIOD_DEFECT> EB_PERIOD_DEFECT { get; set; }
        public virtual DbSet<EB_PERIOD_DEFINE> EB_PERIOD_DEFINE { get; set; }
        public virtual DbSet<EB_PERIOD_EFFICIENCY> EB_PERIOD_EFFICIENCY { get; set; }
        public virtual DbSet<EB_PO_STATUS_HIST> EB_PO_STATUS_HIST { get; set; }
        public virtual DbSet<EB_PROGRESS_TRANS> EB_PROGRESS_TRANS { get; set; }
        public virtual DbSet<EB_SCHEDULE> EB_SCHEDULE { get; set; }
        public virtual DbSet<EB_STATUS> EB_STATUS { get; set; }
        public virtual DbSet<EFFICIENCYLEVEL> EFFICIENCYLEVELs { get; set; }
        public virtual DbSet<EVENTFLOW> EVENTFLOWs { get; set; }
        public virtual DbSet<EVENTFLOWNODE> EVENTFLOWNODEs { get; set; }
        public virtual DbSet<EXCELMAPPING> EXCELMAPPINGs { get; set; }
        public virtual DbSet<FACILITY> FACILITies { get; set; }
        public virtual DbSet<FACILITYEFFICIENCY> FACILITYEFFICIENCies { get; set; }
        public virtual DbSet<FACILITYWORKERNUMBER> FACILITYWORKERNUMBERs { get; set; }
        public virtual DbSet<FACTORY> FACTORies { get; set; }
        public virtual DbSet<Factory_ext> Factory_ext { get; set; }
        public virtual DbSet<factprocessSet_ext> factprocessSet_ext { get; set; }
        public virtual DbSet<FRAMEWORK> FRAMEWORKS { get; set; }
        public virtual DbSet<GRPSERy> GRPSERIES { get; set; }
        public virtual DbSet<GRPTCONDITION> GRPTCONDITIONs { get; set; }
        public virtual DbSet<GRPTDATA> GRPTDATAs { get; set; }
        public virtual DbSet<GRPTDATASOURCE> GRPTDATASOURCEs { get; set; }
        public virtual DbSet<GRPTMASTER> GRPTMASTERs { get; set; }
        public virtual DbSet<HISTORY_EVENTD> HISTORY_EVENTD { get; set; }
        public virtual DbSet<HISTORY_EVENTM> HISTORY_EVENTM { get; set; }
        public virtual DbSet<HOLIDAY> HOLIDAYs { get; set; }
        public virtual DbSet<ID_TABLE> ID_TABLE { get; set; }
        public virtual DbSet<JOBALERT> JOBALERTs { get; set; }
        public virtual DbSet<LANGUAGESETTING> LANGUAGESETTINGs { get; set; }
        public virtual DbSet<LineConnectSeting> LineConnectSetings { get; set; }
        public virtual DbSet<LNCURVEAPPLY> LNCURVEAPPLies { get; set; }
        public virtual DbSet<LNCURVEAPPLYDETAIL> LNCURVEAPPLYDETAILs { get; set; }
        public virtual DbSet<LNCURVEDETAIL> LNCURVEDETAILs { get; set; }
        public virtual DbSet<LNCURVETEMPLATE> LNCURVETEMPLATEs { get; set; }
        public virtual DbSet<LNCURVETEMPLATEAPPLY> LNCURVETEMPLATEAPPLies { get; set; }
        public virtual DbSet<LOADSHARING> LOADSHARINGs { get; set; }
        public virtual DbSet<LOGFILEIMPORT> LOGFILEIMPORTs { get; set; }
        public virtual DbSet<LOGMASTER> LOGMASTERs { get; set; }
        public virtual DbSet<LOGSCHEDULING> LOGSCHEDULINGs { get; set; }
        public virtual DbSet<MACHINEINVENTORY> MACHINEINVENTORies { get; set; }
        public virtual DbSet<macroplan_capacity_loading_ext> macroplan_capacity_loading_ext { get; set; }
        public virtual DbSet<MATERIAL> MATERIALs { get; set; }
        public virtual DbSet<MATERIALRECEIVE> MATERIALRECEIVEs { get; set; }
        public virtual DbSet<MATERIALTEMPLATE> MATERIALTEMPLATEs { get; set; }
        public virtual DbSet<MATERIALTYPE> MATERIALTYPEs { get; set; }
        public virtual DbSet<MODELSETTING> MODELSETTINGS { get; set; }
        public virtual DbSet<MonitorPo_ext> MonitorPo_ext { get; set; }
        public virtual DbSet<ONLINEUSER> ONLINEUSERS { get; set; }
        public virtual DbSet<OPDWF120> OPDWF120 { get; set; }
        public virtual DbSet<OPDWF220> OPDWF220 { get; set; }
        public virtual DbSet<OPDWF220_TOTAL> OPDWF220_TOTAL { get; set; }
        public virtual DbSet<OPDWF320> OPDWF320 { get; set; }
        public virtual DbSet<OPDWF510> OPDWF510 { get; set; }
        public virtual DbSet<OPDWFPatternInfo> OPDWFPatternInfoes { get; set; }
        public virtual DbSet<OPERATIONLOGDETAIL> OPERATIONLOGDETAILs { get; set; }
        public virtual DbSet<OPERATIONLOGMASTER> OPERATIONLOGMASTERs { get; set; }
        public virtual DbSet<ORDERALLOCATIONRULE> ORDERALLOCATIONRULEs { get; set; }
        public virtual DbSet<OTTEVENT> OTTEVENTs { get; set; }
        public virtual DbSet<OTTEVENTPERSON> OTTEVENTPERSONs { get; set; }
        public virtual DbSet<OTTFLOW> OTTFLOWs { get; set; }
        public virtual DbSet<OTTFLOWNODE> OTTFLOWNODEs { get; set; }
        public virtual DbSet<OTTMATERIALCATEGORY> OTTMATERIALCATEGORies { get; set; }
        public virtual DbSet<OTTPARAMETER> OTTPARAMETERs { get; set; }
        public virtual DbSet<OTTPOEVENT> OTTPOEVENTs { get; set; }
        public virtual DbSet<OTTPOSKETCH> OTTPOSKETCHes { get; set; }
        public virtual DbSet<OTTREMARK> OTTREMARKs { get; set; }
        public virtual DbSet<OTTREMARKATTACHEMENT> OTTREMARKATTACHEMENTs { get; set; }
        public virtual DbSet<OTTREMARKINFO> OTTREMARKINFOes { get; set; }
        public virtual DbSet<OTTREMARKSOLOT> OTTREMARKSOLOTs { get; set; }
        public virtual DbSet<PATTERNCAPACITY> PATTERNCAPACITies { get; set; }
        public virtual DbSet<PLANFACILITYPERMISSION> PLANFACILITYPERMISSIONs { get; set; }
        public virtual DbSet<PLANHISTORYDETAIL> PLANHISTORYDETAILs { get; set; }
        public virtual DbSet<PLANHISTORYMASTER> PLANHISTORYMASTERs { get; set; }
        public virtual DbSet<PLANPOPERMISSION> PLANPOPERMISSIONs { get; set; }
        public virtual DbSet<PO> POes { get; set; }
        public virtual DbSet<Po_ext> Po_ext { get; set; }
        public virtual DbSet<POCAPACITY> POCAPACITies { get; set; }
        public virtual DbSet<POCUSTOM> POCUSTOMs { get; set; }
        public virtual DbSet<POCUSTOMCONFIG> POCUSTOMCONFIGs { get; set; }
        public virtual DbSet<PODETAIL> PODETAILs { get; set; }
        public virtual DbSet<POEVENT> POEVENTs { get; set; }
        public virtual DbSet<POLOGDETAIL> POLOGDETAILs { get; set; }
        public virtual DbSet<POLOGMASTER> POLOGMASTERs { get; set; }
        public virtual DbSet<POMACHINE> POMACHINEs { get; set; }
        public virtual DbSet<POMATERIALREQUEST> POMATERIALREQUESTs { get; set; }
        public virtual DbSet<POPROCESSROUTE> POPROCESSROUTEs { get; set; }
        public virtual DbSet<poprocessstatus_ext> poprocessstatus_ext { get; set; }
        public virtual DbSet<PORECIPE> PORECIPEs { get; set; }
        public virtual DbSet<POSIZEORDERED> POSIZEORDEREDs { get; set; }
        public virtual DbSet<PROCESS> PROCESSes { get; set; }
        public virtual DbSet<process_ext> process_ext { get; set; }
        public virtual DbSet<Processdailydata_ext> Processdailydata_ext { get; set; }
        public virtual DbSet<PROCESSEVENTMAPPING> PROCESSEVENTMAPPINGs { get; set; }
        public virtual DbSet<PROCESSROUTE> PROCESSROUTEs { get; set; }
        public virtual DbSet<PROCESSROUTENODE> PROCESSROUTENODEs { get; set; }
        public virtual DbSet<PRODUCTIONEVENT> PRODUCTIONEVENTs { get; set; }
        public virtual DbSet<PRODUCTIONEVENTCAPACITY> PRODUCTIONEVENTCAPACITies { get; set; }
        public virtual DbSet<PRODUCTIONEVENTDETAIL> PRODUCTIONEVENTDETAILs { get; set; }
        public virtual DbSet<PRODUCTIONSCHEDULE> PRODUCTIONSCHEDULEs { get; set; }
        public virtual DbSet<PRODUCTPROCESSCAPACITY> PRODUCTPROCESSCAPACITies { get; set; }
        public virtual DbSet<PRODUCTTYPE> PRODUCTTYPEs { get; set; }
        public virtual DbSet<PRODUCTTYPECAPACITY> PRODUCTTYPECAPACITies { get; set; }
        public virtual DbSet<REF> REFs { get; set; }
        public virtual DbSet<REPORTSETTING> REPORTSETTINGs { get; set; }
        public virtual DbSet<REPORTSETTINGDETAIL> REPORTSETTINGDETAILs { get; set; }
        public virtual DbSet<ROLEFRAMEPOPEDOM> ROLEFRAMEPOPEDOMS { get; set; }
        public virtual DbSet<ROLEJOBPOPEDOM> ROLEJOBPOPEDOMS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<SCHEDULEPARAM> SCHEDULEPARAMs { get; set; }
        public virtual DbSet<SCOREGROUP> SCOREGROUPs { get; set; }
        public virtual DbSet<SCOREGROUPITEM> SCOREGROUPITEMs { get; set; }
        public virtual DbSet<SCORETEMPLATE> SCORETEMPLATEs { get; set; }
        public virtual DbSet<SCORETEMPLATEGROUP> SCORETEMPLATEGROUPs { get; set; }
        public virtual DbSet<SCORETEMPLATEGROUPITEM> SCORETEMPLATEGROUPITEMs { get; set; }
        public virtual DbSet<Sewingdailydata_ext> Sewingdailydata_ext { get; set; }
        public virtual DbSet<SPECIALCALENDAR> SPECIALCALENDARs { get; set; }
        public virtual DbSet<STYLEINFO> STYLEINFOS { get; set; }
        public virtual DbSet<SwitchTime> SwitchTimes { get; set; }
        public virtual DbSet<USERPREFERENCE> USERPREFERENCEs { get; set; }
        public virtual DbSet<USERROLE> USERROLES { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<VIEWDATAPERMISSION> VIEWDATAPERMISSIONs { get; set; }
        public virtual DbSet<WORKCALENDAR> WORKCALENDARs { get; set; }
        public virtual DbSet<WORKCALENDARAPPLY> WORKCALENDARAPPLies { get; set; }
        public virtual DbSet<WORKSHOP> WORKSHOPs { get; set; }
        public virtual DbSet<BI_DAILY_LOADING> BI_DAILY_LOADING { get; set; }
        public virtual DbSet<BI_PO> BI_PO { get; set; }
        public virtual DbSet<BI_PO_DATA> BI_PO_DATA { get; set; }
        public virtual DbSet<DMLOGFILE> DMLOGFILEs { get; set; }
        public virtual DbSet<DMPO> DMPOes { get; set; }
        public virtual DbSet<DMPOCUSTOM> DMPOCUSTOMs { get; set; }
        public virtual DbSet<DMPODETAIL> DMPODETAILs { get; set; }
        public virtual DbSet<DMPOSIZEDETAIL> DMPOSIZEDETAILs { get; set; }
        public virtual DbSet<OPDWF510Split> OPDWF510Split { get; set; }
        public virtual DbSet<POIMAGE> POIMAGES { get; set; }
        public virtual DbSet<POSIZEDETAIL> POSIZEDETAILs { get; set; }
        public virtual DbSet<PROCESSRULE> PROCESSRULEs { get; set; }
        public virtual DbSet<PROTYPECAPACITYLOG> PROTYPECAPACITYLOGs { get; set; }
        public virtual DbSet<EXT_V_PO> EXT_V_PO { get; set; }
    }
}
