//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPDWF510
    {
        public string RCID { get; set; }
        public string DELF { get; set; }
        public string SONO { get; set; }
        public Nullable<int> LOT { get; set; }
        public string CRNM { get; set; }
        public Nullable<int> PRIO { get; set; }
        public string ODTY { get; set; }
        public string ODST { get; set; }
        public string NCTR { get; set; }
        public string CSSE { get; set; }
        public string PRGM { get; set; }
        public string CSNM { get; set; }
        public string CUNM { get; set; }
        public string CUSY { get; set; }
        public string CFTY { get; set; }
        public string SYD1 { get; set; }
        public string SYCO { get; set; }
        public Nullable<double> GTMH { get; set; }
        public string GTST { get; set; }
        public string OTDD { get; set; }
        public string COTD { get; set; }
        public string OTTD { get; set; }
        public string UOTT { get; set; }
        public string AOTT { get; set; }
        public string PPRO { get; set; }
        public Nullable<int> ACQY { get; set; }
        public Nullable<int> ECQY { get; set; }
        public Nullable<int> QTYN { get; set; }
        public string FIRM { get; set; }
        public string REMK { get; set; }
        public string COLR { get; set; }
        public string SZE { get; set; }
        public string SHIP { get; set; }
        public string SMOD { get; set; }
        public string UPUS { get; set; }
        public string UPNM { get; set; }
        public string UPDT { get; set; }
        public string CSNO { get; set; }
        public string POTT { get; set; }
        public string ALTF { get; set; }
        public string EVENTFLOWNAME { get; set; }
        public string PROCESSROUTENAME { get; set; }
        public string LNGP { get; set; }
        public string PLCORDDATE { get; set; }
        public string MASTERMATERIALDATE { get; set; }
        public string MASTERMATERIALRECEIVEDDATE { get; set; }
        public string MATERIALDATE { get; set; }
        public string MATERIALRECEIVEDDATE { get; set; }
        public string CODE { get; set; }
        public string CUSTOMERORDERNO { get; set; }
        public string FACTORYVIEWDATEDAYS { get; set; }
        public string GROUPID { get; set; }
        public string TURNSINGLE { get; set; }
        public string SETNO { get; set; }
        public string BARCHARTDISPLAY { get; set; }
        public string LASTPRODUCTDATE { get; set; }
        public string DREMARKS { get; set; }
        public string CUSTOMTXT1 { get; set; }
        public string CUSTOMTXT2 { get; set; }
        public string CUSTOMTXT3 { get; set; }
        public string CUSTOMTXT4 { get; set; }
        public string CUSTOMTXT5 { get; set; }
        public string CUSTOMTXT6 { get; set; }
        public string CUSTOMDDL1 { get; set; }
        public string CUSTOMDDL2 { get; set; }
        public string CUSTOMDDL3 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE1 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE2 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE3 { get; set; }
        public Nullable<double> CUSTOMNUMBER1 { get; set; }
        public Nullable<double> CUSTOMNUMBER2 { get; set; }
        public Nullable<double> CUSTOMNUMBER3 { get; set; }
        public Nullable<double> UNITPRICE { get; set; }
        public string ORDERTYPE { get; set; }
        public Nullable<System.DateTime> MATERIALSET { get; set; }
        public string POSOURCE { get; set; }
        public Nullable<int> ORIGINALQTYN { get; set; }
        public string MaterialNO { get; set; }
        public string Brand { get; set; }
        public string Require { get; set; }
        public string Logo { get; set; }
        public string Components { get; set; }
        public string ProcurementReview { get; set; }
    }
}
