//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPDWF320
    {
        public string RCID { get; set; }
        public string DELF { get; set; }
        public string POCODE { get; set; }
        public string MATERIALCODE { get; set; }
        public string MATERIALNAME { get; set; }
        public string MATERIALCOLOR { get; set; }
        public string MATERIALSIZE { get; set; }
        public Nullable<int> MATERIALSTYLE { get; set; }
        public Nullable<int> EFFECTEDSTARTTIME { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public string UNIT { get; set; }
        public Nullable<int> EALINESSPERCENT { get; set; }
        public string MPNO { get; set; }
        public string SUPPLIER { get; set; }
        public string SUPPLIERART { get; set; }
        public string MPDATE { get; set; }
        public Nullable<double> MPAMOUNT { get; set; }
        public string MPUNIT { get; set; }
        public string EXPECTEDRECIVEDATE { get; set; }
        public string FINISHEDDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string DECLAREDATA { get; set; }
        public string QUALIFIED { get; set; }
        public string SHRINKAGE { get; set; }
        public string DECLARETESTMARKS { get; set; }
        public string SAILDATE { get; set; }
        public Nullable<System.DateTime> LASTACTUALDATE { get; set; }
        public Nullable<double> ACTUALAMOUNT { get; set; }
        public string CUSTOMTXT1 { get; set; }
        public string CUSTOMTXT2 { get; set; }
        public string CUSTOMTXT3 { get; set; }
        public string CUSTOMTXT4 { get; set; }
        public string CUSTOMTXT5 { get; set; }
        public string CUSTOMTXT6 { get; set; }
        public string CUSTOMDATE1 { get; set; }
        public string CUSTOMDATE2 { get; set; }
        public string CUSTOMDATE3 { get; set; }
        public Nullable<double> CUSTOMNUMBER1 { get; set; }
        public Nullable<double> CUSTOMNUMBER2 { get; set; }
        public Nullable<double> CUSTOMNUMBER3 { get; set; }
    }
}
