//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPDWF220_TOTAL
    {
        public int ID { get; set; }
        public string POCODE { get; set; }
        public string PROCESS { get; set; }
        public string FACILITY { get; set; }
        public string PDATE { get; set; }
        public string COLOR { get; set; }
        public string XSIZE { get; set; }
        public int QTY { get; set; }
        public Nullable<int> WORKERS { get; set; }
        public Nullable<double> DECWORKERS { get; set; }
        public Nullable<double> HOURS { get; set; }
        public Nullable<double> OTHOURS { get; set; }
        public Nullable<int> FPY { get; set; }
        public string REMARKS { get; set; }
        public string BATCH { get; set; }
    }
}
