//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTTFLOWNODE
    {
        public int ID { get; set; }
        public Nullable<int> OTTFLOWID { get; set; }
        public Nullable<int> OTTEVENTID { get; set; }
        public string PREVNODEID { get; set; }
        public string NEXTNODEID { get; set; }
        public Nullable<double> DURATION { get; set; }
        public Nullable<int> ISAFFECTPLAN { get; set; }
        public Nullable<int> GRAPHICX { get; set; }
        public Nullable<int> GRAPHICY { get; set; }
        public string DESCRIPTION { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
