//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTTPOEVENT
    {
        public decimal ID { get; set; }
        public decimal POID { get; set; }
        public decimal OTTFLOWNODEID { get; set; }
        public Nullable<double> DURATION { get; set; }
        public Nullable<System.DateTime> UPDFINISHDATE { get; set; }
        public Nullable<System.DateTime> ACTFINISHDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string SALESORDERNO { get; set; }
        public string LOTNO { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> ORGFINISHDATE { get; set; }
        public string ALERT { get; set; }
        public Nullable<int> TYPEFLAG { get; set; }
    }
}
