//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANHISTORYDETAIL
    {
        public int PLANHISTORYMASTERID { get; set; }
        public int PRODUCTIONEVENTID { get; set; }
        public string CODE { get; set; }
        public string LINE { get; set; }
        public string PRODUCTTYPE { get; set; }
        public string CUSTOMER { get; set; }
        public string PATTERN { get; set; }
        public string CUSTOMERSTYLENO { get; set; }
        public Nullable<int> ORDERQTY { get; set; }
        public Nullable<int> PLANAMOUNT { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public Nullable<double> EFFICIENCY { get; set; }
        public Nullable<System.DateTime> DELIVERYDATE { get; set; }
        public Nullable<System.DateTime> REQFINISHEDDATE { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
    
        public virtual PLANHISTORYMASTER PLANHISTORYMASTER { get; set; }
    }
}
