//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Po_ext
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ProducttypeID { get; set; }
        public string ProducttypeName { get; set; }
        public string customerstyleno { get; set; }
        public string Pattern { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<double> Sam { get; set; }
        public Nullable<int> Factoryid { get; set; }
        public string FactoryName { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<System.DateTime> Deliverydate { get; set; }
        public Nullable<System.DateTime> WorkDeliverydate { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<int> Troubletype { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<int> EVENTFLOWID { get; set; }
        public Nullable<int> PROCESSROUTEID { get; set; }
        public Nullable<int> start_facilityid { get; set; }
        public Nullable<int> end_facilityid { get; set; }
        public Nullable<System.DateTime> InitDeliverydate { get; set; }
        public string Merchandiser { get; set; }
    }
}
