//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCUSTOM
    {
        public int POID { get; set; }
        public string CUSTOMTXT1 { get; set; }
        public string CUSTOMTXT2 { get; set; }
        public string CUSTOMTXT3 { get; set; }
        public string CUSTOMTXT4 { get; set; }
        public string CUSTOMTXT5 { get; set; }
        public string CUSTOMTXT6 { get; set; }
        public string CUSTOMDDL1 { get; set; }
        public string CUSTOMDDL2 { get; set; }
        public string CUSTOMDDL3 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE1 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE2 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE3 { get; set; }
        public Nullable<double> CUSTOMNUMBER1 { get; set; }
        public Nullable<double> CUSTOMNUMBER2 { get; set; }
        public Nullable<double> CUSTOMNUMBER3 { get; set; }
    
        public virtual PO PO { get; set; }
    }
}
