//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODETAIL
    {
        public PODETAIL()
        {
            this.POSIZEDETAILs = new HashSet<POSIZEDETAIL>();
        }
    
        public int ID { get; set; }
        public int POID { get; set; }
        public string CUSTOMERORDERNO { get; set; }
        public string POCOLOR { get; set; }
        public double AMOUNT { get; set; }
        public System.DateTime DELIVERYDATE { get; set; }
        public Nullable<int> FACTORYVIEWDATEDAYS { get; set; }
        public string EXCOUNTRY { get; set; }
        public string EXTYPE { get; set; }
        public Nullable<System.DateTime> MASTERMATERIALDATE { get; set; }
        public Nullable<System.DateTime> MASTERMATERIALRECEIVEDDATE { get; set; }
        public Nullable<System.DateTime> MATERIALDATE { get; set; }
        public Nullable<System.DateTime> MATERIALRECEIVEDDATE { get; set; }
        public Nullable<System.DateTime> PREPRODUCTIONEVENTDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> Homogeneity { get; set; }
        public Nullable<int> STATE { get; set; }
        public Nullable<System.DateTime> SubDatetime { get; set; }
    
        public virtual PO PO { get; set; }
        public virtual ICollection<POSIZEDETAIL> POSIZEDETAILs { get; set; }
    }
}
