//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POEVENT
    {
        public int ID { get; set; }
        public int POID { get; set; }
        public int EVENTFLOWNODEID { get; set; }
        public Nullable<double> DURATION { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ISAFFECTPLAN { get; set; }
        public Nullable<System.DateTime> STANDARDTIME { get; set; }
        public Nullable<System.DateTime> STARTDATEUPDATEDATE { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> KPIDate { get; set; }
        public Nullable<int> BaseDataID { get; set; }
        public Nullable<int> DelayFinishDateCauseBaseDataID { get; set; }
        public Nullable<System.DateTime> InitKPIDate { get; set; }
    
        public virtual EVENTFLOWNODE EVENTFLOWNODE { get; set; }
        public virtual PO PO { get; set; }
    }
}
