//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLOGDETAIL
    {
        public int ID { get; set; }
        public Nullable<int> OPERATIONID { get; set; }
        public Nullable<int> POID { get; set; }
        public Nullable<int> DETAILID { get; set; }
        public string XSIZE { get; set; }
        public string FIELDNAME { get; set; }
        public string OLDVALUE { get; set; }
        public string NEWVALUE { get; set; }
        public string FIELDTYPE { get; set; }
        public int OPERATEFLAG { get; set; }
    }
}
