//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POMATERIALREQUEST
    {
        public int ID { get; set; }
        public int POID { get; set; }
        public string MATERIALCODE { get; set; }
        public string MATERIALNAME { get; set; }
        public string MATERIALCOLOR { get; set; }
        public string MATERIALSIZE { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public string UNIT { get; set; }
        public Nullable<double> DURATION { get; set; }
        public Nullable<int> MATERIALSTYLE { get; set; }
        public Nullable<int> EFFECTEDSTARTTIME { get; set; }
        public string MPNO { get; set; }
        public Nullable<System.DateTime> MPDATE { get; set; }
        public Nullable<double> MPAMOUNT { get; set; }
        public string MPUNIT { get; set; }
        public Nullable<System.DateTime> EXPECTEDRECIVEDATE { get; set; }
        public Nullable<System.DateTime> FINISHEDDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string FIELD1 { get; set; }
        public string FIELD2 { get; set; }
        public Nullable<int> EALINESSPERCENT { get; set; }
        public string CATEGORY { get; set; }
        public string SUPPLIER { get; set; }
        public string SUPPLIERART { get; set; }
        public Nullable<System.DateTime> UPDDLVDATE { get; set; }
        public Nullable<System.DateTime> LATELYRECEIVEDATE { get; set; }
        public string STATUS { get; set; }
        public string PODESTINATION { get; set; }
        public string GRDESTINATION { get; set; }
        public string ALERT { get; set; }
        public string SOKEYID { get; set; }
        public string BOMKEYID { get; set; }
        public Nullable<double> WASTAGEPERCENTAGE { get; set; }
        public Nullable<double> CONVERSIONFACTOR { get; set; }
        public Nullable<int> INVALIDOTTCALC { get; set; }
        public Nullable<int> EXENDFIELD_INT_1 { get; set; }
        public Nullable<int> EXENDFIELD_INT_2 { get; set; }
        public Nullable<double> EXENDFIELD_DBL_3 { get; set; }
        public Nullable<double> EXENDFIELD_DBL_4 { get; set; }
        public Nullable<System.DateTime> EXENDFIELD_DATE_5 { get; set; }
        public Nullable<System.DateTime> EXENDFIELD_DATE_6 { get; set; }
        public string EXENDFIELD_CHAR_7 { get; set; }
        public string EXENDFIELD_CHAR_8 { get; set; }
        public string EXENDFIELD_CHAR_9 { get; set; }
        public string EXENDFIELD_CHAR_10 { get; set; }
        public string PURCHASER { get; set; }
        public string EMAIL { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string MARKS { get; set; }
        public Nullable<System.DateTime> DECLAREDATA { get; set; }
        public string QUALIFIED { get; set; }
        public string SHRINKAGE { get; set; }
        public string DECLARETESTMARKS { get; set; }
        public Nullable<System.DateTime> SAILDATE { get; set; }
        public Nullable<System.DateTime> LASTACTUALDATE { get; set; }
        public Nullable<double> ACTUALAMOUNT { get; set; }
    }
}
