//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class poprocessstatus_ext
    {
        public int Typeid { get; set; }
        public int poid { get; set; }
        public int processid { get; set; }
        public Nullable<int> status { get; set; }
    }
}
