//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORECIPE
    {
        public int ID { get; set; }
        public int POID { get; set; }
        public string POCOLOR { get; set; }
        public string POSIZE { get; set; }
        public string EXCOUNTRY { get; set; }
        public string MATERIALCODE { get; set; }
        public string MATERIALNAME { get; set; }
        public string MATERIALCOLOR { get; set; }
        public string MATERIALSIZE { get; set; }
        public double AMOUNT { get; set; }
        public string UNIT { get; set; }
        public double DURATION { get; set; }
        public int MATERIALSTYLE { get; set; }
        public int EFFECTEDSTARTTIME { get; set; }
        public string DESCRIPTION { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    
        public virtual PO PO { get; set; }
    }
}
