//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSROUTENODE
    {
        public PROCESSROUTENODE()
        {
            this.POPROCESSROUTEs = new HashSet<POPROCESSROUTE>();
        }
    
        public int ID { get; set; }
        public int PROCESSROUTEID { get; set; }
        public int PROCESSID { get; set; }
        public string PREVNODEID { get; set; }
        public string NEXTNODEID { get; set; }
        public Nullable<int> OFFSETTYPE { get; set; }
        public Nullable<double> OFFSETDAYS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> GRAPHICX { get; set; }
        public Nullable<int> GRAPHICY { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<int> PROCESSSEQ { get; set; }
    
        public virtual ICollection<POPROCESSROUTE> POPROCESSROUTEs { get; set; }
        public virtual PROCESS PROCESS { get; set; }
        public virtual PROCESSROUTE PROCESSROUTE { get; set; }
    }
}
