//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS
    {
        public PROCESS()
        {
            this.FACILITies = new HashSet<FACILITY>();
            this.MACHINEINVENTORies = new HashSet<MACHINEINVENTORY>();
            this.PATTERNCAPACITies = new HashSet<PATTERNCAPACITY>();
            this.PRODUCTPROCESSCAPACITies = new HashSet<PRODUCTPROCESSCAPACITY>();
            this.PROCESSROUTENODEs = new HashSet<PROCESSROUTENODE>();
            this.PRODUCTIONSCHEDULEs = new HashSet<PRODUCTIONSCHEDULE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ISPRIMARY { get; set; }
        public string DESCRIPTION { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    
        public virtual ICollection<FACILITY> FACILITies { get; set; }
        public virtual ICollection<MACHINEINVENTORY> MACHINEINVENTORies { get; set; }
        public virtual ICollection<PATTERNCAPACITY> PATTERNCAPACITies { get; set; }
        public virtual ICollection<PRODUCTPROCESSCAPACITY> PRODUCTPROCESSCAPACITies { get; set; }
        public virtual ICollection<PROCESSROUTENODE> PROCESSROUTENODEs { get; set; }
        public virtual ICollection<PRODUCTIONSCHEDULE> PRODUCTIONSCHEDULEs { get; set; }
    }
}
