//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class process_ext
    {
        public int Type { get; set; }
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<int> isprimary { get; set; }
        public Nullable<int> matchtype { get; set; }
        public Nullable<int> matchprocessid { get; set; }
        public Nullable<int> active { get; set; }
    }
}
