//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTTYPE
    {
        public PRODUCTTYPE()
        {
            this.POes = new HashSet<PO>();
            this.PRODUCTPROCESSCAPACITies = new HashSet<PRODUCTPROCESSCAPACITY>();
            this.PRODUCTTYPECAPACITies = new HashSet<PRODUCTTYPECAPACITY>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public Nullable<double> EFFICIENCY { get; set; }
        public Nullable<int> FACTORYID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string DESCRIPTION { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    
        public virtual ICollection<PO> POes { get; set; }
        public virtual ICollection<PRODUCTPROCESSCAPACITY> PRODUCTPROCESSCAPACITies { get; set; }
        public virtual ICollection<PRODUCTTYPECAPACITY> PRODUCTTYPECAPACITies { get; set; }
    }
}
