//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTIONEVENTDETAIL
    {
        public int ID { get; set; }
        public int PRODUCTIONEVENTID { get; set; }
        public int POID { get; set; }
        public int PODETAILID { get; set; }
        public string POCOLOR { get; set; }
        public string POSIZE { get; set; }
        public double AMOUNT { get; set; }
        public double PLANAMOUNT { get; set; }
        public string CODE { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public string CUSTOMERORDERID { get; set; }
        public Nullable<int> PRODUCTTYPEID { get; set; }
        public string PATTERN { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public Nullable<int> MERCHANDISER { get; set; }
        public Nullable<int> FACTORYID { get; set; }
        public Nullable<int> EVENTFLOWID { get; set; }
        public Nullable<int> PROCESSROUTEID { get; set; }
        public Nullable<int> ISFIRMORDER { get; set; }
        public Nullable<System.DateTime> DELIVERYDATE { get; set; }
        public Nullable<int> FACTORYVIEWDATEDAYS { get; set; }
        public string EXCOUNTRY { get; set; }
        public string EXTYPE { get; set; }
        public Nullable<System.DateTime> MASTERMATERIALDATE { get; set; }
        public Nullable<System.DateTime> MASTERMATERIALRECEIVEDDATE { get; set; }
        public Nullable<System.DateTime> MATERIALDATE { get; set; }
        public Nullable<System.DateTime> MATERIALRECEIVEDDATE { get; set; }
        public Nullable<System.DateTime> PREPRODUCTIONEVENTDATE { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public Nullable<double> EFFICIENCY { get; set; }
        public Nullable<int> UPDATEEFFSTATE { get; set; }
        public Nullable<double> PLANCAPACITY { get; set; }
        public Nullable<double> PLANEFFICIENCY { get; set; }
        public string DESCRIPTION { get; set; }
        public string SALESORDERNO { get; set; }
        public Nullable<int> PARENTPRODUCTTYPEID { get; set; }
        public string REFNO { get; set; }
        public Nullable<double> INITCAPACITY { get; set; }
        public Nullable<System.DateTime> CAOTD { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<double> FINISHEDAMOUNT { get; set; }
        public string FINISHEDAMOUNTFROM { get; set; }
    
        public virtual FACTORY FACTORY { get; set; }
        public virtual PO PO { get; set; }
        public virtual PRODUCTIONEVENT PRODUCTIONEVENT { get; set; }
    }
}
