//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROTYPECAPACITYLOG
    {
        public int ID { get; set; }
        public int CUSTOMERID { get; set; }
        public int PRODUCTTYPEID { get; set; }
        public int FACILITYID { get; set; }
        public int LEVELID { get; set; }
        public Nullable<double> OLDEFFICIENCY { get; set; }
        public Nullable<double> NEWEFFICIENCY { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
