//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF
    {
        public int REFTYPE { get; set; }
        public string REFCD { get; set; }
        public string PARENTCD { get; set; }
        public string DESC1 { get; set; }
        public string DESC2 { get; set; }
        public string DESC3 { get; set; }
        public string REMARKS { get; set; }
    }
}
