//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTSETTING
    {
        public int ID { get; set; }
        public string REPORTNAME { get; set; }
        public string COLUMNNAME { get; set; }
        public string HEADERTEXT { get; set; }
        public string LANGUAGETYPE { get; set; }
        public string COLUMNDES { get; set; }
        public string DATATYPE { get; set; }
        public Nullable<int> SEQ { get; set; }
        public Nullable<int> VISIBLE { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string USERTEXT { get; set; }
    }
}
