//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLEFRAMEPOPEDOM
    {
        public int ID { get; set; }
        public int ROLEID { get; set; }
        public int FRAMEID { get; set; }
        public Nullable<int> POPEDOMID { get; set; }
    
        public virtual FRAMEWORK FRAMEWORK { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
