//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULEPARAM
    {
        public int ID { get; set; }
        public Nullable<int> SCORETEMPLATEID { get; set; }
        public Nullable<int> ISCOMPELEARLESTDATE { get; set; }
        public Nullable<int> PLANSELECTTYPE { get; set; }
        public Nullable<int> NOTCOMPELDAYS { get; set; }
        public Nullable<int> DELIVERYDATEDAYS { get; set; }
        public Nullable<int> FIRSTSELECTPLANAMOUNT { get; set; }
        public Nullable<int> SUITLIMITFACILITY { get; set; }
    
        public virtual SCORETEMPLATE SCORETEMPLATE { get; set; }
    }
}
