//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCOREGROUP
    {
        public SCOREGROUP()
        {
            this.SCORETEMPLATEGROUPs = new HashSet<SCORETEMPLATEGROUP>();
        }
    
        public int ID { get; set; }
        public string SCOREGROUPCODE { get; set; }
        public string SCOREGROUPNAME { get; set; }
        public Nullable<int> VIEWORD { get; set; }
        public string GROUPBACKCOLOR { get; set; }
        public Nullable<int> ISVISIBLE { get; set; }
    
        public virtual ICollection<SCORETEMPLATEGROUP> SCORETEMPLATEGROUPs { get; set; }
    }
}
