//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCORETEMPLATE
    {
        public SCORETEMPLATE()
        {
            this.SCHEDULEPARAMs = new HashSet<SCHEDULEPARAM>();
            this.SCORETEMPLATEGROUPs = new HashSet<SCORETEMPLATEGROUP>();
        }
    
        public int ID { get; set; }
        public string SCORETEMPLATECODE { get; set; }
        public string SCORETEMPLATENAME { get; set; }
        public Nullable<int> TEMPLATETYPEID { get; set; }
        public Nullable<int> VIEWORD { get; set; }
        public Nullable<int> ISDEFAULT { get; set; }
        public Nullable<int> ISINIT { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    
        public virtual ICollection<SCHEDULEPARAM> SCHEDULEPARAMs { get; set; }
        public virtual ICollection<SCORETEMPLATEGROUP> SCORETEMPLATEGROUPs { get; set; }
    }
}
