//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCORETEMPLATEGROUP
    {
        public SCORETEMPLATEGROUP()
        {
            this.SCORETEMPLATEGROUPITEMs = new HashSet<SCORETEMPLATEGROUPITEM>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SCORETEMPLATEID { get; set; }
        public Nullable<int> SCOREGROUPID { get; set; }
        public Nullable<int> GROUPSCALE { get; set; }
        public Nullable<int> ISENABLED { get; set; }
    
        public virtual SCOREGROUP SCOREGROUP { get; set; }
        public virtual SCORETEMPLATE SCORETEMPLATE { get; set; }
        public virtual ICollection<SCORETEMPLATEGROUPITEM> SCORETEMPLATEGROUPITEMs { get; set; }
    }
}
