//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCOREGROUPITEM
    {
        public SCOREGROUPITEM()
        {
            this.SCORETEMPLATEGROUPITEMs = new HashSet<SCORETEMPLATEGROUPITEM>();
        }
    
        public int ID { get; set; }
        public string SCOREGROUPITEMCODE { get; set; }
        public string SCOREGROUPITEMNAME { get; set; }
        public Nullable<int> VIEWORD { get; set; }
        public string OPRCHAR { get; set; }
        public string SCOREFONTCOLOR { get; set; }
    
        public virtual ICollection<SCORETEMPLATEGROUPITEM> SCORETEMPLATEGROUPITEMs { get; set; }
    }
}
