//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STYLEINFO
    {
        public string ID { get; set; }
        public string STYLENO { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public string PRODUCTTYPE { get; set; }
        public string PROCESSROUTE { get; set; }
        public string EVENTFLOW { get; set; }
        public string CUSTOMERSTYLENO { get; set; }
        public string STYLEDESC { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
