//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.PLANFACILITYPERMISSIONs = new HashSet<PLANFACILITYPERMISSION>();
            this.PLANPOPERMISSIONs = new HashSet<PLANPOPERMISSION>();
            this.USERPREFERENCEs = new HashSet<USERPREFERENCE>();
            this.USERROLES = new HashSet<USERROLE>();
            this.VIEWDATAPERMISSIONs = new HashSet<VIEWDATAPERMISSION>();
        }
    
        public int ID { get; set; }
        public string ACCOUNT { get; set; }
        public string PASS_WORD { get; set; }
        public string USERNAME { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string TITLENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> LOGINED { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> FACTORYID { get; set; }
        public Nullable<System.DateTime> LASTLOGINTIME { get; set; }
        public Nullable<int> CANIMPORTDATA { get; set; }
        public Nullable<int> LEADERID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ISDILLARDS { get; set; }
        public string ALERTEMAIL { get; set; }
        public Nullable<int> ISTASKWARN { get; set; }
        public Nullable<int> RECEIVEDMMAIL { get; set; }
    
        public virtual ICollection<PLANFACILITYPERMISSION> PLANFACILITYPERMISSIONs { get; set; }
        public virtual ICollection<PLANPOPERMISSION> PLANPOPERMISSIONs { get; set; }
        public virtual ICollection<USERPREFERENCE> USERPREFERENCEs { get; set; }
        public virtual ICollection<USERROLE> USERROLES { get; set; }
        public virtual ICollection<VIEWDATAPERMISSION> VIEWDATAPERMISSIONs { get; set; }
    }
}
